# Generated by Django 3.0.7 on 2020-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='end_year',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='series',
            name='start_year',
            field=models.IntegerField(default=-1),
        ),
    ]
