# Generated by Django 3.0.7 on 2020-09-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_api', '0004_auto_20200902_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(default=-1)),
                ('death_year', models.IntegerField(default=-1)),
                ('primary_profession', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='popularity',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=-1)),
                ('category', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('characters', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='ratings_api.Actor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='ratings_api.Episode')),
            ],
        ),
    ]
