# Generated by Django 3.0.7 on 2020-09-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_api', '0006_auto_20200905_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='known_for',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
