# Generated by Django 3.0.7 on 2020-08-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField(default=-1)),
                ('episode_number', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
                ('primary_title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(default=1775)),
                ('end_year', models.IntegerField(default=2175)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=-1.0)),
                ('num_votes', models.IntegerField(default=-1)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings_api.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=200)),
                ('original_name', models.CharField(max_length=200)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings_api.Episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings_api.Series'),
        ),
    ]
