# Generated by Django 3.0.7 on 2020-08-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_api', '0002_auto_20200802_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='ratings_api.Series'),
        ),
        migrations.AlterField(
            model_name='episodename',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='ratings_api.Episode'),
        ),
        migrations.AlterField(
            model_name='episoderating',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings_api.Episode'),
        ),
    ]
